language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
before_deploy: "./gradlew assembleDist"
sudo: false
deploy:
  provider: releases
  api_key:
    secure: DzdK3o3QFvQtKGtHl74j9geBg5uaFnasQXrNWWb5SRBfjDAhjQd49Ju5Pu8n5+W2SMUvB5w4KXepmHgu4R8Q9jo9tI/oTN6XB+0RJE+09rNQfeUEcYM6PLrBt0AZLfcQqkWxNkW+KvwhGb080loPKoTLI6VtLenkG19T4/z/qxo=
  file:
    - build/distributions/ical4j-$RELEASE_VERSION.zip
    - build/distributions/ical4j-$RELEASE_VERSION.tar.gz
  skip_cleanup: true
  on:
    tags: true
after_script:
  - sudo keytool -import -alias sonar -keystore $JAVA_HOME/jre/lib/security/cacerts -file sonar_cert.pem -storepass changeit -noprompt
  # Check if commit is not a pull request, if git repo is official, and if branch is master. If checks pass, run Sonar reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ical4j/ical4j-vcard ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew sonarqube"

